i2s_audio:
  id: i2s_in
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

microphone:
  - platform: i2s_audio
    id: mic_i2s
    channel: left
    adc_type: external
    i2s_din_pin: "${i2s_din_pin}"  # SD
    i2s_audio_id: i2s_in
    pdm: false
    on_data:
      - logger.log:
          format: "Received %d bytes"
          args: ['x.size()']

esphome:
  min_version: 2023.10.0
  on_boot:
    - priority: -100
      then:
        - wait_until: api.connected
        - delay: 1s
        - wait_until: microphone.capture
        - delay: 1s
        - logger.log: "Microphone started!"
